### ISSUE TITLE
Combined designs are saved as one

### ISSUE THREAD

**Issue by mp-dthr** [javierarce/figma-extractor#3]
Hi,
First of all, great package, keep up with the great work. 👏 

I tried to export multiple designs from Figma file, but I noticed that some elements are saved as one, even though sometimes I want to separate them. The root cause is that some elements are created within the same frame.

Is there a way to download each element from the selected frame separately?

**Comment by javierarce** [comment]
Sorry for the late reply, @mp-dthr. The package operates at the frame level, meaning it doesn't export frames nested within other frames. It only downloads the frames that are at the root level of each page.
